export const SeedCategories: { [key: string]: string[] } = {
  vehicles: [
    'cars',
    'motorbikes',
    'caravans',
    'utilities',
    'auto-equipment',
    'motorbike-equipment',
  ],
  'real-estate': ['real-estate-sales', 'rentals', 'roommates', 'offices-and-shops'],
  electronics: [
    'computers',
    'computer-accessories',
    'image-and-sound',
    'phones-and-connected-objects',
    'video-games',
    'consoles',
    'tablets-and-e-readers',
  ],
  'home-and-garden': [
    'furnishing',
    'decoration',
    'household-linen',
    'diy',
    'gardening',
    'appliances',
  ],
  fashion: ['clothing', 'shoes', 'accessories-and-luggage', 'watches-and-jewelry'],
  leisure: [
    'movies',
    'music',
    'books',
    'antiques',
    'toys-and-games',
    'musical-instruments',
    'collectibles',
    'modeling',
    'bikes',
    'wine-and-gastronomy',
  ],
  animals: ['pets', 'accessories', 'lost-animals'],
  services: [
    'artists-and-musicians',
    'babysitting',
    'events',
    'carpooling',
    'neighbor-help',
    'tutoring',
    'moving',
    'guardianship',
    'gardening-service',
    'cleaning',
    'repairs',
    'personal-service',
    'other-services',
  ],
  'professional-equipment': [
    'agricultural-equipment',
    'tractors',
    'heavy-duty',
    'transport-and-handling',
    'construction-and-heavy-work',
    'tools',
    'industrial-equipment',
    'restaurant-and-hotel',
    'office-supplies',
    'materials',
    'medical-equipment',
  ],
};
