export const SeedCategories: {
  [key: string]: (string | { value: string; illustration?: { uuid: string; extension: string } })[];
} = {
  vehicles: [
    { value: 'cars', illustration: { uuid: 'seed_cars', extension: 'jpg' } },
    { value: 'motorbikes', illustration: { uuid: 'seed_motorbikes', extension: 'jpg' } },
    'caravans',
    'utilities',
    'auto-equipment',
    'motorbike-equipment',
  ],
  'real-estate': [
    {
      value: 'real-estate-sales',
      illustration: { uuid: 'seed_real-estate-sales', extension: 'jpg' },
    },
    'rentals',
    'roommates',
    'offices-and-shops',
  ],
  electronics: [
    'computers',
    'computer-accessories',
    'image-and-sound',
    'phones-and-connected-objects',
    { value: 'video-games', illustration: { uuid: 'seed_video-games', extension: 'jpg' } },
    'tablets-and-e-readers',
  ],
  'home-and-garden': [
    { value: 'furnishing', illustration: { uuid: 'seed_furnishing', extension: 'jpg' } },
    'decoration',
    'household-linen',
    'diy',
    'gardening',
    'appliances',
  ],
  fashion: [
    { value: 'clothing', illustration: { uuid: 'seed_clothing', extension: 'jpg' } },
    'shoes',
    'accessories-and-luggage',
    'watches-and-jewelry',
  ],
  leisure: [
    'movies',
    'music',
    { value: 'books', illustration: { uuid: 'seed_books', extension: 'jpg' } },
    'antiques',
    'toys-and-games',
    'musical-instruments',
    'collectibles',
    'modeling',
    'bikes',
    'wine-and-gastronomy',
  ],
  animals: ['pets', 'accessories', 'lost-animals'],
  services: [
    'artists-and-musicians',
    'babysitting',
    'events',
    'carpooling',
    'neighbor-help',
    'tutoring',
    'moving',
    'guardianship',
    'gardening-service',
    'cleaning',
    'repairs',
    'personal-service',
    'other-services',
  ],
  'professional-equipment': [
    'agricultural-equipment',
    'tractors',
    'heavy-duty',
    'transport-and-handling',
    'construction-and-heavy-work',
    'tools',
    'industrial-equipment',
    'restaurant-and-hotel',
    'office-supplies',
    'materials',
    'medical-equipment',
  ],
};
